### PR TITLE
Add Prometheus metrics to aiops-publisher

### PR DESCRIPTION
**Pull request by AparnaKarve**
Added the following `Counter` based metrics -
- aiops_publisher_post_requests_total
- aiops_publisher_post_requests_successful
- aiops_publisher_post_requests_exceptions

Also added the `metrics` endpoint to swagger.yml

### CODE REVIEW

**Comment by tumido** [comment]
@AparnaKarve ^ talking about your test above, that's exactly where I see the issue... I don't think we want this behavior. Let's have this metric, which should be telling us what's the amount of total successful requests. And the values on Prometheus may look like:

chart 1


How would you know what is the total value? And how do you know to which pod each point belongs to?
This is how it looks like when I color code it:

chart

If a new pod spawns, it starts from zero and when a pod is terminated the amount of hits on that pod gets buried somewhere in the rest of the data.. I don't think a metric like this is useful at all.

What we're aiming for with Prometheus? What kind of data we want to know? Let's go back to the drawing board and figure out what we actually want to see. If we want to have the total amount of successful hits, we need to output one number - and the number should be the same no matter which pod you ask for it. If we want to know how many requests a specific pod had, we need to keep the lifecycle in mind and we need to be able to tell the data apart.

**Comment by AparnaKarve** [comment]
I came across some new information today with regards to aggregating the metrics across multiple pods.

We essentially need 2 things -
- a few changes in the Prometheus config yaml and 
- a few annotations to the publisher service

The below doc describes all the details - 

https://docs.google.com/document/d/1ruC0XkkuySYyMPDE0kq_ALQG-ynZ-g7Xkabhkcn-5sQ/edit

I am currently in the process of trying out the steps listed in the doc.

As far as the metrics implementation in this PR goes, we are good.
and as far as metric type goes, we can always add more metric types in follow-up PRs once the basic implementation is in.

**Comment by tumido** [comment]
@AparnaKarve I see! That explains something! :+1: About the Prometheus configs and stuff: This sounds a bit "official" :wink: - we have to add our namespace to their configs. Therefore it would be nice to have some official namespace. Currently we're using many test/dev deployments but all of them have strange names, like `aiops-clustering-integration`, `tcoufal-aiops-playground`, `aiops-test-pipeline`. We should have one proper setup which we're gonna advertise in these configs.

Let's do this, then: I'm gonna deploy the pipeline once more. Now, we're gonna call it `aiops-clustering`, since that's the first service we're integrating... So, I'll deploy it and update the permissions a policies, and you'll do the mnm PR. Sounds good? :slightly_smiling_face:

**Comment by tumido** [comment]
@AparnaKarve so.. I've deployed the `aiops-clustering` project https://console.insights-dev.openshift.com/console/project/aiops-clustering (you should have admin rights). I've also updated the roles for according that doc you've linked above:

```
$ oc policy add-role-to-user view system:serviceaccount:prometheus:prometheus -n aiops-clustering
$ oc policy add-role-to-user view system:serviceaccount:mnm-ci:default -n aiops-clustering
```

image


Is there anything else about this PR which needs to be adjusted? My only concern was if we can separate metrics from different pods, and if the docs says this are the only steps needed I don't see an issue here. What do you think? Anything else blocking this PR?

**Comment by AparnaKarve** [comment]
Awesome @tumido  -- this will definitely make the testing easy!

**Pull request merged**
